framework:
    annotations:
        cache: oro.cache.annotations
    session:
        handler_id: snc_redis.session.handler
doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id:   oro.cache.doctrine.metadata
                query_cache_driver:
                    type: service
                    id:   oro.cache.doctrine.query
            config:
                metadata_cache_driver:
                    type: service
                    id:   oro.cache.doctrine.metadata.config
                query_cache_driver:
                    type: service
                    id:   oro.cache.doctrine.query.config
            search:
                metadata_cache_driver:
                    type: service
                    id:   oro.cache.doctrine.metadata.search
                query_cache_driver:
                    type: service
                    id:   oro.cache.doctrine.query.search
snc_redis:
    clients:  # configure phpredis clients
        default:
            type: predis
            alias: default
            dsn: "%redis_dsn_cache%"
        doctrine:
            type: predis
            alias: doctrine
            dsn: "%redis_dsn_doctrine%"
        session:
            type: predis
            alias: session
            dsn: "%redis_dsn_session%"
    session:  # configure sessions
        client: session
        prefix: session
        use_as_default: true

jms_serializer:
    metadata:
        cache: Metadata\Cache\DoctrineCacheAdapter
